name: main
on: push

jobs:
  build:
    name: main build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd build
        cmake --build .
